version: "2.1"
services:

  mysql:
    build: ./database
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - docker_xxx
    environment:
      - MYSQL_ROOT_PASSWORD=acklw
      - MYSQL_DATABASE=WoxDB
      - MYSQL_USER=user
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "3306:3306"

  node:
    build: ./server_side_package
    container_name: node
    ports:
      - "3001:3001"
    volumes:
      - ./database/image_uploads:/usr/src/app/image_uploads
      - ./database/compressed_image_uploads:/usr/src/app/compressed_image_uploads
      - ./client-site-web-builder/build:/usr/src/app/web-builder/build
      - ./visitor-default-view/build:/usr/src/app/visitor/build
    networks:
      - docker_xxx
    environment:
      - DATABASE_PORT=3306
      - SERVER_PORT=3001
      - DATABASE_HOST=mysql
      - DATABASE_PASSWORD=acklw

networks:
  docker_xxx:
    driver: bridge