version: "2"
services:

  mysql:
    build: ./database
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - docker_xxx
    environment:
      - MYSQL_ROOT_PASSWORD=acklw
      - MYSQL_DATABASE=WoxDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passwd
    volumes:
      - ./database/data:/data/mysql
    ports:
      - "3306:3306"

  node:
    build: ./server_side_package
    container_name: node
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - docker_xxx
    environment:
      - PORT=3001
      - DATABASE_HOST=mysql
      - DATABASE_PASSWORD=acklw
      - EGG_SERVER_ENV=local
      - NODE_ENV=development

networks:
  docker_xxx:
    driver: bridge
